version: '3'

services:
  yp-web:
    image: evgfitil/yp-webinar
    container_name: yp-web
    command: gunicorn wsgi:app -w 4 --bind 0:5000
    networks:
      - yp
    expose:
      - 5000
  nginx:
    build: ./nginx
    container_name: yp-nginx
    expose:
      - 80
    networks:
      - yp
      - traefik
    depends_on:
      - yp-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx_yp.rule=Host(`test.ea-praktikum.ml`)"
      - "traefik.http.routers.nginx_yp.entrypoints=websecure"
      - "traefik.http.routers.nginx_yp.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external:
      name: traefik
  yp:
    external: false